name: Dev CI/CD
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

env:
  CI: false
#   env_dev: ${{ secrets.ENV_DEV }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #   - name: import env file
      #     run: |
      #       touch ./.env && echo "$env_dev" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #   - name: docker login
      #     uses: docker/login-action@v3
      #     with:
      #       username: ${{ secrets.DOCKERHUB_USERNAME }}
      #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Rahat-UI Image
      - name: build && push rahat-ui
        id: build-push-rahat-ui
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          #   push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          push: false
          tags: esatya/rahat-ui:dev
