name: AA Test Load

on:
  push:
    branches:
      - test-load
  workflow_dispatch:

jobs:
  call-core:
    uses: rahataid/rahat-projetc-aa/.github/workflows/AA-Core-CICD.yaml@test-load
    with:
      image_name: beneficiary,rahat
      dockerfile_path: Dockerfile.aa
      tag_suffix: test-load
    secrets: inherit
